# Generated by Django 4.1.5 on 2023-01-09 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kom_name', models.CharField(default=False, max_length=20, verbose_name='Имя комментатора')),
                ('kom_text', models.TextField(null=True, verbose_name='Текст комментария')),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.AlterModelOptions(
            name='texts',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='comments',
            name='numbers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.texts', verbose_name='ид новости'),
        ),
    ]
